### ISSUE TITLE
Matches view - New game button gives error

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/MokStats#9]
gives error 

[07/Jan/2018 03:15:18] "GET /admin/login/?next=/admin/mokstats/match/add/ HTTP/1.1" 200 1691
Traceback (most recent call last):
  File "c:\bin\python27\Lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "c:\bin\python27\Lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "c:\bin\python27\Lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "c:\bin\python27\Lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "c:\bin\python27\Lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "c:\bin\python27\Lib\socket.py", line 328, in write
    self.flush()
  File "c:\bin\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
[07/Jan/2018 03:15:19] "GET /admin/login/?next=/admin/mokstats/match/add/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63204)
Traceback (most recent call last):
  File "c:\bin\python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\bin\python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\bin\python27\Lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "c:\bin\python27\Lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "c:\bin\python27\Lib\socket.py", line 283, in close
    self.flush()
  File "c:\bin\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by Andrioden** [comment]
Unable to recreate
